### ISSUE TITLE
Documentation: Add instructions to include the file

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/grid#7]
I am missing a step in the installation instructions to include the `../../bower_components/grid/_grid.scss` file.

**Comment by haroldangenent** [comment]
Marking this as wontfix, for these reasons:
- This is common sense and should not be documented. Everyone who uses this mixin should know how to use Bower and it's components;
- If you forget to do this, you'll get an error;
- This can be done in so many different ways than a plain include that this cannot be properly documented.
